u20681047_HW03/Controllers/BarController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
//using System.Xml.Linq;
using u18347852_HW03.Models;
using GemBox.Document;

namespace u18347852_HW03.Controllers
{
    public class BarController : Controller
    {
        // GET: Bar
        public ActionResult Reporting()
        {
            // Define the start and end dates for the period you want to analyze
            DateTime startDate = new DateTime(2023, 1, 1); // Replace with your desired start date
            DateTime endDate = new DateTime(2023, 12, 31); // Replace with your desired end date

            // Call the GetBorrowCountForBooks method to retrieve the data
            List<DataPoint> borrowData = DATA.GetBorrowCountForBooks(startDate, endDate);

            // Pass the data to the view
            ViewBag.BorrowData = borrowData;

            return View();
        }

        public ActionResult Archives()
        {
            string[] filePaths = Directory.GetFiles(Server.MapPath("~/Documents/"));
            List<FileModel> files = new List<FileModel>();
            foreach (string filePath in filePaths)
            {
                files.Add(new FileModel { FileName = Path.GetFileName(filePath) });
            }
            return View(files);
        }
        public FileResult DownloadFile(string fileName)
        {
            string path = Server.MapPath("~/Documents/") + fileName;
            byte[] bytes = System.IO.File.ReadAllBytes(path);
            return File(bytes, "application/octet-stream", fileName);
        }

        public ActionResult DeleteFile(string fileName)
        {
            string path = Server.MapPath("~/Documents/") + fileName;
            byte[] bytes = System.IO.File.ReadAllBytes(path);


            System.IO.File.Delete(path);

            return RedirectToAction("Reporting");
        }

        public FileResult DisplayFile(string fileName)
        {
            string path = Server.MapPath("~/Documents/") + fileName;
            byte[] bytes = System.IO.File.ReadAllBytes(path);
            return File(bytes, System.Net.Mime.MediaTypeNames.Application.Octet, fileName);
        }

        public ActionResult TinyMCE() => this.View(new FileModel());

        [HttpPost]
        public FileResult SaveReport(FileModel model)
        {
            // If using Professional version, put your serial key below.
            ComponentInfo.SetLicense("FREE-LIMITED-KEY");

            var templateFile = Server.MapPath("~/App_Data/DocumentTemplate.docx");

            // Load template document.
            var document = DocumentModel.Load(templateFile);

            // Insert content from HTML editor.
            var bookmark = document.Bookmarks["HtmlBookmark"];
            bookmark.GetContent(true).LoadText(model.Content, LoadOptions.HtmlDefault);

            // Save document to stream in specified format.
            var saveOptions = GetSaveOptions(model.Extension);
            var stream = new MemoryStream();
            document.Save(stream, saveOptions);

            // Download document.
            var downloadDirectory = Server.MapPath("~/Documents/");
            var downloadFile = $"{model.FileName}{model.Extension}";
            var fullPath = Path.Combine(downloadDirectory, downloadFile);
            System.IO.File.WriteAllBytes(fullPath, stream.ToArray());

            string[] filePaths = Directory.GetFiles(Server.MapPath("~/Documents/"));
            List<FileModel> files = new List<FileModel>();
            foreach (string filePath in filePaths)
            {
                files.Add(new FileModel { FileName = Path.GetFileName(filePath) });
            }
            return File(fullPath, saveOptions.ContentType, downloadFile);
        }

        private static SaveOptions GetSaveOptions(string extension)
        {
            switch (extension)
            {
                case ".docx": return SaveOptions.DocxDefault;
                case ".pdf": return SaveOptions.PdfDefault;
                case ".xps": return SaveOptions.XpsDefault;
                case ".html": return SaveOptions.HtmlDefault;
                case ".mhtml": return new HtmlSaveOptions() { HtmlType = HtmlType.Mhtml };
                case ".rtf": return SaveOptions.RtfDefault;
                case ".xml": return SaveOptions.XmlDefault;
                case ".png": return SaveOptions.ImageDefault;
                case ".jpeg": return new ImageSaveOptions(ImageSaveFormat.Jpeg);
                case ".gif": return new ImageSaveOptions(ImageSaveFormat.Gif);
                case ".bmp": return new ImageSaveOptions(ImageSaveFormat.Bmp);
                case ".tiff": return new ImageSaveOptions(ImageSaveFormat.Tiff);
                case ".wmp": return new ImageSaveOptions(ImageSaveFormat.Wmp);
                default: return SaveOptions.TxtDefault;
            }
        }

    }
}

u20681047_HW03/Views/Bar/Archives.cshtml
@using u18347852_HW03.Models
@model List<FileModel>
@{
    ViewBag.Title = "File Example";
}

<script src="~/Scripts/Viewer/fileViewer.js"></script>
<div>
    <h4>Documents of any file type</h4>
</div>
<div style="height: 400px; overflow: auto;">
    <table class="table table-hover">
        <thead style="position: sticky; top: 0; background-color: lightgrey;">
            <tr>
                <th width="75%">FILE NAME</th>
                <th>DOWNLOAD</th>
                <th>DELETE</th>
            </tr>
        </thead>
        @foreach (FileModel file in Model)
        {
            <tr>
                <td>@file.FileName</td>
                <td class="t">@Html.ActionLink("Download", "DownloadFile", new { fileName = file.FileName }, new { @class = "btn btn-success btn-sm", style = "width: 150px;" })</td>
                <td class="t">@Html.ActionLink("Delete", "DeleteFile", new { fileName = file.FileName }, new { @class = "btn btn-danger btn-sm", style = "width: 150px;" })</td>
            </tr>


        }
    </table>
</div>

u20681047_HW03/Views/Bar/Reporting.cshtml
@model u18347852_HW03.Models.FileModel

@{
    ViewBag.Title = "Borrowed Books Chart";
}
<link href="~/Content/Site.css" rel="stylesheet" />
<script src="~/Scripts/jquery-3.7.1.min.js"></script>
<script src="~/scripts/tinymce/tinymce.min.js"></script>
@using (Html.BeginForm("SaveReport", "Bar", FormMethod.Post))
{
    <div class="form-group">
        @Html.TextBoxFor(model => model.FileName, new { @class = "form-control", style = "width: 300px;", placeholder = "Add File Name" })
   
        @Html.DropDownListFor(model => model.Extension,
              new[]
              {
                new SelectListItem() { Text = "DOCX", Value = ".docx" },
                new SelectListItem() { Text = "PDF", Value = ".pdf", Selected = true },
                new SelectListItem() { Text = "XPS", Value = ".xps" },
                new SelectListItem() { Text = "HTML", Value = ".html" },
                new SelectListItem() { Text = "MHTML", Value = ".mhtml" },
                new SelectListItem() { Text = "RTF", Value = ".rtf" },
                new SelectListItem() { Text = "XML", Value = ".xml" },
                new SelectListItem() { Text = "TXT", Value = ".txt" },
                new SelectListItem() { Text = "PNG", Value = ".png" },
                new SelectListItem() { Text = "JPEG", Value = ".jpeg" },
                new SelectListItem() { Text = "GIF", Value = ".gif" },
                new SelectListItem() { Text = "BMP", Value = ".bmp" },
                new SelectListItem() { Text = "TIFF", Value = ".tiff" },
                new SelectListItem() { Text = "WMP", Value = ".wmp" }
              },
                new { @class = "form-control", style = "width: 150px;" })
    </div>
    <div style="padding-right: 15px; padding-left: 15px;">
        <input type="submit" class="btn btn-primary" value="Save" style="width: 150px;" disabled />
    </div>

    <div id="chartContainer">
        @Html.TextAreaFor(model => model.Content, new { id = "file-editor" })
    </div>
}






<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.min.js"></script>
<script src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script type="text/javascript">
  $(document).ready(function () {
        var borrowData = @Html.Raw(Json.Encode(ViewBag.BorrowData));

        var dataPoints = borrowData.map(function (item) {
            return { y: item.Y, label: item.Label };
        });
        console.log(dataPoints)
        var chart = new CanvasJS.Chart("chartContainer", {
            title: {
                text: "Number of Times Each Book Has Been Borrowed"
            },
            animationEnabled: true,
            axisX: {
                title: "Books"
            },
            axisY: {
                title: "Number of Borrows"
            },
            data: [
                {
                    type: "bar",
                    name: "Borrows",
                    dataPoints: dataPoints
                }
            ]
        });

        chart.render();
    });

    $(document).ready(function () {
        // Enable the Download button when the file name field is not empty
        var fileNameField = $("input[name='FileName']");
        fileNameField.on("input", function () {
            var fileName = fileNameField.val();
            var saveButton = $("input[type='submit'][value='Save']");
            if (fileName.length > 0) {
                saveButton.prop("disabled", false);
            } else {
                saveButton.prop("disabled", true);
            }
        });
    });
</script>