u20681047_HW03/Controllers/authorsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using u18347852_HW03.Models;

namespace u18347852_HW03.Controllers
{
    public class authorsController : Controller
    {
        private LibraryEntities db = new LibraryEntities();

        // GET: authors
        public ActionResult Index()
        {
            return View(db.authors.ToList());
        }

        // GET: authors/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            authors authors = db.authors.Find(id);
            if (authors == null)
            {
                return HttpNotFound();
            }
            return View(authors);
        }

        // GET: authors/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: authors/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "authorId,name,surname")] authors authors)
        {
            if (ModelState.IsValid)
            {
                db.authors.Add(authors);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(authors);
        }

        // GET: authors/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            authors authors = db.authors.Find(id);
            if (authors == null)
            {
                return HttpNotFound();
            }
            return View(authors);
        }

        // POST: authors/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "authorId,name,surname")] authors authors)
        {
            if (ModelState.IsValid)
            {
                db.Entry(authors).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(authors);
        }

        // GET: authors/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            authors authors = db.authors.Find(id);
            if (authors == null)
            {
                return HttpNotFound();
            }
            return View(authors);
        }

        // POST: authors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            authors authors = db.authors.Find(id);
            db.authors.Remove(authors);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

u20681047_HW03/Controllers/booksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using u18347852_HW03.Models;

namespace u18347852_HW03.Controllers
{
    public class booksController : Controller
    {
        private LibraryEntities db = new LibraryEntities();

        // GET: books
        public ActionResult Index()
        {
            var books = db.books.Include(b => b.authors).Include(b => b.types);
            return View(books.ToList());
        }

        // GET: books/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            books books = db.books.Find(id);
            if (books == null)
            {
                return HttpNotFound();
            }
            return View(books);
        }

        // GET: books/Create
        public ActionResult Create()
        {
            ViewBag.authorId = new SelectList(db.authors, "authorId", "name");
            ViewBag.typeId = new SelectList(db.types, "typeId", "name");
            return View();
        }

        // POST: books/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "bookId,name,pagecount,point,authorId,typeId")] books books)
        {
            if (ModelState.IsValid)
            {
                db.books.Add(books);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.authorId = new SelectList(db.authors, "authorId", "name", books.authorId);
            ViewBag.typeId = new SelectList(db.types, "typeId", "name", books.typeId);
            return View(books);
        }

        // GET: books/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            books books = db.books.Find(id);
            if (books == null)
            {
                return HttpNotFound();
            }
            ViewBag.authorId = new SelectList(db.authors, "authorId", "name", books.authorId);
            ViewBag.typeId = new SelectList(db.types, "typeId", "name", books.typeId);
            return View(books);
        }

        // POST: books/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "bookId,name,pagecount,point,authorId,typeId")] books books)
        {
            if (ModelState.IsValid)
            {
                db.Entry(books).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.authorId = new SelectList(db.authors, "authorId", "name", books.authorId);
            ViewBag.typeId = new SelectList(db.types, "typeId", "name", books.typeId);
            return View(books);
        }

        // GET: books/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            books books = db.books.Find(id);
            if (books == null)
            {
                return HttpNotFound();
            }
            return View(books);
        }

        // POST: books/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            books books = db.books.Find(id);
            db.books.Remove(books);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

u20681047_HW03/Controllers/borrowsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using u18347852_HW03.Models;

namespace u18347852_HW03.Controllers
{
    public class borrowsController : Controller
    {
        private LibraryEntities db = new LibraryEntities();

        // GET: borrows
        public ActionResult Index()
        {
            var borrows = db.borrows.Include(b => b.books).Include(b => b.students);
            return View(borrows.ToList());
        }

        // GET: borrows/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            borrows borrows = db.borrows.Find(id);
            if (borrows == null)
            {
                return HttpNotFound();
            }
            return View(borrows);
        }

        // GET: borrows/Create
        public ActionResult Create()
        {
            ViewBag.bookId = new SelectList(db.books, "bookId", "name");
            ViewBag.studentId = new SelectList(db.students, "studentId", "name");
            return View();
        }

        // POST: borrows/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "borrowId,studentId,bookId,takenDate,broughtDate")] borrows borrows)
        {
            if (ModelState.IsValid)
            {
                db.borrows.Add(borrows);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.bookId = new SelectList(db.books, "bookId", "name", borrows.bookId);
            ViewBag.studentId = new SelectList(db.students, "studentId", "name", borrows.studentId);
            return View(borrows);
        }

        // GET: borrows/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            borrows borrows = db.borrows.Find(id);
            if (borrows == null)
            {
                return HttpNotFound();
            }
            ViewBag.bookId = new SelectList(db.books, "bookId", "name", borrows.bookId);
            ViewBag.studentId = new SelectList(db.students, "studentId", "name", borrows.studentId);
            return View(borrows);
        }

        // POST: borrows/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "borrowId,studentId,bookId,takenDate,broughtDate")] borrows borrows)
        {
            if (ModelState.IsValid)
            {
                db.Entry(borrows).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.bookId = new SelectList(db.books, "bookId", "name", borrows.bookId);
            ViewBag.studentId = new SelectList(db.students, "studentId", "name", borrows.studentId);
            return View(borrows);
        }

        // GET: borrows/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            borrows borrows = db.borrows.Find(id);
            if (borrows == null)
            {
                return HttpNotFound();
            }
            return View(borrows);
        }

        // POST: borrows/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            borrows borrows = db.borrows.Find(id);
            db.borrows.Remove(borrows);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

u20681047_HW03/Controllers/typesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using u18347852_HW03.Models;

namespace u18347852_HW03.Controllers
{
    public class typesController : Controller
    {
        private LibraryEntities db = new LibraryEntities();

        // GET: types
        public ActionResult Index()
        {
            return View(db.types.ToList());
        }

        // GET: types/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            types types = db.types.Find(id);
            if (types == null)
            {
                return HttpNotFound();
            }
            return View(types);
        }

        // GET: types/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: types/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "typeId,name")] types types)
        {
            if (ModelState.IsValid)
            {
                db.types.Add(types);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(types);
        }

        // GET: types/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            types types = db.types.Find(id);
            if (types == null)
            {
                return HttpNotFound();
            }
            return View(types);
        }

        // POST: types/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "typeId,name")] types types)
        {
            if (ModelState.IsValid)
            {
                db.Entry(types).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(types);
        }

        // GET: types/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            types types = db.types.Find(id);
            if (types == null)
            {
                return HttpNotFound();
            }
            return View(types);
        }

        // POST: types/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            types types = db.types.Find(id);
            db.types.Remove(types);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

u20681047_HW03/Views/Home/Index.cshtml
@model u18347852_HW03.Models.bookstudentVM
<style>
    * {
        margin: 0;
        padding: 0;
        box-sizing: border-box;
    }

    .table:hover {
        cursor: pointer;
    }
</style>
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.11.6/css/jquery.dataTables.min.css">

<div>
    <img src="~/images/Home.png" style="width: 1280px; height: 400px" ;>

    
</div>


<div class="row">
    <div class="col-6">
        <!-- Students Table -->
        <p>
            <a href="#" class="create-link" data-url="@Url.Action("Create", "students")">Create a Student</a>
        </p>
        <table class="table table-striped table-hover table-primary">
            <thead>
                <tr class="table-dark">
                    <th>Student ID</th>
                    <th>Name</th>
                    <th>Surname</th>
                    <th>Birthdate</th>
                    <th>Gender</th>
                    <th>Class</th>
                    <th>Point</th>
                </tr>
            </thead>
            <tbody id="StudentTable">
                @foreach (var item in Model.students)
                {
                    <tr>
                        <td>@item.studentId</td>
                        <td>@item.name</td>
                        <td>@item.surname</td>
                        <td>@item.birthdate</td>
                        <td>@item.gender</td>
                        <td>@(item.@class)</td>
                        <td>@item.point</td>
                    </tr>
                }
            </tbody>
        </table>
        <div class="col-md-12 text-center">
            <div class="pagination" id="studentPagination">
                <button class="btn btn-secondary" id="prevStudentPage">Previous</button>
                <span id="studentPageInfo">Page <span id="currentStudentPage">1</span> of <span id="totalStudentPages">1</span></span>
                <button class="btn btn-primary" id="nextStudentPage">Next</button>
            </div>
        </div>
    </div>
    <div class="col-6">
        <!-- Books Table -->
        <p>
            <a href="#" class="create-book-link" data-url="@Url.Action("Create", "books")">Create a Book</a>
        </p>
        <table class="table table-striped table-hover table-primary">
            <thead>
                <tr class="table-dark">
                    <th>Book ID</th>
                    <th>Name</th>
                    <th>Page Count</th>
                    <th>Point</th>
                    <th>Author ID</th>
                    <th>Type ID</th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody id="BookTable">
                @foreach (var item in Model.books)
                {
                    string status = "Available";
                    var borrow = item.borrows.OrderByDescending(b => b.takenDate).FirstOrDefault();
                    if (borrow != null && borrow.broughtDate == null)
                    {
                        status = "Out";
                    }
                    <tr>
                        <td>@item.bookId</td>
                        <td>@item.name</td>
                        <td>@item.pagecount</td>
                        <td>@item.point</td>
                        <td>@item.authorId</td>
                        <td>@item.typeId</td>
                        <td>@status</td>
                    </tr>
                }
            </tbody>


        </table>
        <div class="pagination" id="bookPagination">
            <button class="btn btn-secondary" id="prevBookPage">Previous</button>
            <span id="bookPageInfo">Page <span id="currentBookPage">1</span> of <span id="totalBookPages">1</span></span>
            <button class="btn btn-primary" id="nextBookPage">Next</button>
        </div>
    </div>
</div>

<!------------------------------MODAL------------------------>
<div id="myModal" class="modal fade" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">My Library</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body" id="modal-content">
            </div>
        </div>
    </div>
</div>



<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="~/Scripts/MyScript.js"></script>

u20681047_HW03/Views/Home/Maintain.cshtml
@model u18347852_HW03.Models.borrwauthortypeVM
<style>
    * {
        margin: 0;
        padding: 0;
        box-sizing: border-box;
    }
   
    .update-button {
        color: #fff;
        background-color: #007BFF; 
        border-color: #007BFF; 
    }

   
    .delete-button {
        color: #fff;
        background-color: #DC3545; 
        border-color: #DC3545; 
    }

    .table:hover {
        cursor: pointer;
    }
</style>
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.11.6/css/jquery.dataTables.min.css">
<div class="row">
    <div class="col-6">
        <!-- Author Table -->
        <p>
            <a href="#" class="create-link" data-url="@Url.Action("Create", "authors")">Create an Author</a>
        </p>
        <table class="table table-striped table-hover table-primary">
            <thead>
                <tr class="table-dark">
                    <th>Author ID</th>
                    <th>Name</th>
                    <th>Surname</th>
                    <th>Operations</th>
                </tr>
            </thead>
            <tbody id="AuthorTable">
                @foreach (var item in Model.authors)
                {
                    <tr>
                        <td>@item.authorId</td>
                        <td>@item.name</td>
                        <td>@item.surname</td>
                        <td>
                            <a href="#" class="edit-link btn btn-primary update-button" data-url="@Url.Action("Edit", "authors", new {id = item.authorId})">Update</a>
                            <a href="#" class="delete-link btn btn-danger delete-button" data-url="@Url.Action("Delete", "authors", new {id = item.authorId})">Delete</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        <div class="col-md-12 text-center">
            <div class="pagination" id="authorPagination">
                <button class="btn btn-secondary" id="prevAuthorPage">Previous</button>
                <span id="authorPageInfo">Page <span id="currentAuthorPage">1</span> of <span id="totalAuthorPages">1</span></span>
                <button class="btn btn-primary" id="nextAuthorPage">Next</button>
            </div>
        </div>
    </div>
    <div class="col-6">
        <!-- Types Table -->
        <p>
            <a href="#" class="create-book-link" data-url="@Url.Action("Create", "types")">Create Type</a>
        </p>
        <table class="table table-striped table-hover table-primary">
            <thead>
                <tr class="table-dark">
                    <th>Type ID</th>
                    <th>Name</th>
                    <th>Operations</th>
                </tr>
            </thead>
            <tbody id="TypeTable">
                @foreach (var item in Model.types)
                {
                    <tr>
                        <td>@item.typeId</td>
                        <td>@item.name</td>
                        <td>
                            <a href="#" class="edit-link btn btn-primary update-button" data-url="@Url.Action("Edit", "types", new {id = item.typeId})">Update</a>
                            <a href="#" class="delete-link btn btn-danger delete-button" data-url="@Url.Action("Delete", "types", new {id = item.typeId})">Delete</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        <div class="pagination" id="typePagination">
            <button class="btn btn-secondary" id="prevTypePage">Previous</button>
            <span id="typePageInfo">Page <span id="currentTypePage">1</span> of <span id="totalTypePages">1</span></span>
            <button class="btn btn-primary" id="nextTypePage">Next</button>
        </div>
    </div>
</div>
<br />
<br />
<!--Borrows Table-->
<div class="container">
    <div class="row">
        <div class="col-12">
            <p>
                <a href="#" class="create-link" data-url="@Url.Action("Create", "borrows")">Create a Borrow</a>
            </p>
            <table class="table table-success table-striped ">
                <thead>
                    <tr class="table-dark">
                        <th>Borrow ID</th>
                        <th>Student ID</th>
                        <th>Book ID</th>
                        <th>Taken Date</th>
                        <th>Brought Date</th>
                        <th>Operations</th>
                    </tr>
                </thead>
                <tbody id="BorrowTable">
                    @foreach (var item in Model.borrows)
                    {
                        <tr>
                            <td>@item.borrowId</td>
                            <td>@item.studentId</td>
                            <td>@item.bookId</td>
                            <td>@item.takenDate</td>
                            <td>@item.broughtDate</td>
                            <td>
                                <a href="#" class="edit-link btn btn-primary update-button-button" data-url="@Url.Action("Edit", "borrows", new {id = item.borrowId})">Update</a>
                                <a href="#" class="delete-link btn btn-danger delete-button" data-url="@Url.Action("Delete", "borrows", new {id = item.borrowId})">Delete</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
            <div class="col-md-12 text-center">
                <div class="pagination" id="borrowPagination">
                    <button class="btn btn-secondary" id="prevBorrowPage">Previous</button>
                    <span id="borrowPageInfo">Page <span id="currentBorrowPage">1</span> of <span id="totalBorrowPages">1</span></span>
                    <button class="btn btn-primary" id="nextBorrowPage">Next</button>
                </div>
            </div>
        </div>
    </div>
</div>

<!------------------------------MODAL------------------------>
<div id="myModal" class="modal fade" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">My Library</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body" id="modal-content">
            </div>
        </div>
    </div>
</div>



<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="~/Scripts/MyScript2.js"></script>